apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.claim.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
