apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: NodePort
  ports:
    - port: {{.Values.port }}
  selector:
    app: {{ .Values.labels.app }}