server:
  port: 8086
spring:
  rabbitmq:
    addresses: amqp://test:test@127.0.0.1:5672
#    amqp://admin:secret@localhost
#    username: test
#    password: test
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: music-transfer-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://192.168.59.100/keycloak/auth/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://192.168.59.100/keycloak/auth/realms/SpringBootKeycloak

app.resource.server:
  url: localhost:8085/api

logging:
  level:
    com.music.transfer.thymeleaf.feign.AppResourceServerFeignClient: DEBUG
feign:
  client:
    config:
      resource-server:
        requestInterceptors:
          - com.music.transfer.thymeleaf.feign.interceptor.FeignRequestAuthHeaderInterceptor
        loggerLevel: FULL