springCloudVersion = 2023.0.1
org.springframework.boot.version = 3.2.5
io.spring.dependency-management.version = 1.1.4
mapstruct.version = 1.5.5.Final
lombok.version = 1.18.24
lombok.mapstruct.binding.version = 0.2.0
telegrambot.starter.version = 7.2.1
scribejava.version = 8.3.3
jwt.version = 4.4.0
expiringmap.version = 0.5.11
org.gradle.java.home = /home/user/java_projects/jdk-17.0.7