replicas: 1

# start: create OpenShift realm which is required by EDP
#extraInitContainers: |
#  - name: realm-provider
#    image: busybox
#    imagePullPolicy: IfNotPresent
#    command:
#      - sh
#    args:
#      - -c
#      - |
#        echo '{"realm": "openshift","enabled": true}' > /opt/keycloak/data/import/openshift.json
#    volumeMounts:
#      - name: realm
#        mountPath: /opt/keycloak/data/import

# The following parameter is unrecommended to expose. Exposed health checks lead to an unnecessary attack vector.
health:
  enabled: false
# The following parameter is unrecommended to expose. Exposed metrics lead to an unnecessary attack vector.
metrics:
  enabled: false

#extraVolumeMounts: |
#  - name: realm
#    mountPath: /opt/keycloak/data/import
#
#extraVolumes: |
#  - name: realm
#    emptyDir: {}

command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--auto-build"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"
  - "--http-relative-path=/keycloak/auth"
#  - "--import-realm"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-creds
        key: username
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.awt.headless=true
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

# This block should be uncommented if you install Keycloak on Kubernetes
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: cookie
    # НЕ УБИРАТЬ!!!!!!!!
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/rewrite-target: /keycloak/$1

  # The following parameter is unrecommended to expose. Admin paths lead to an unnecessary attack vector.
  console:
    enabled: false
  rules:
    - host: ""
      paths:
        - path: /keycloak/(.*)
          pathType: Prefix

# This block should be uncommented if you set Keycloak to OpenShift and change the host field
# route:
#   enabled: false
#   # Path for the Route
#   path: '/'
#   # Host name for the Route
#   host: "keycloak.<ROOT_DOMAIN>"
#   # TLS configuration
#   tls:
#     enabled: true

resources:
  limits:
    memory: "2048Mi"
  requests:
    cpu: "50m"
    memory: "512Mi"

# Check database readiness at startup
dbchecker:
  enabled: true

database:
  vendor: postgres
  existingSecret: keycloak-postgresql
  hostname: postgresql
  port: 5432
  username: admin
  database: keycloak