apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - port: {{ .Values.port.forward }}
      targetPort: {{ .Values.port.original }}